import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
        Facebook Clone
        </h1>

       </main>
    </div>
  )
}
