import Head from 'next/head'

import Homepage from './home'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <div id="fb-root"></div>
      </Head>

      <main>
        <h1>Facebook Clone</h1>
        <Homepage />
      </main>
    </div>
  )
}
