import Head from 'next/head'

import Homepage from './home'

const Home = () => (
  <>
    <Head>
      <title>Facebook Clone</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1>Facebook Clone</h1>
      <Homepage />
    </main>
  </>
)

export default Home
